### ISSUE TITLE
Question about running

### ISSUE THREAD

**Issue by Jerryme-xxm** [sachin-chhabra/PyTorch-ViT-MNIST#1]
Thanks for your great work!

I want to run your code, but there is an error.

    Traceback (most recent call last):
      File "main.py", line 50, in <module>
        main(args)
      File "main.py", line 10, in main
        solver = Solver(args)
      File "/home/ikenaga/xiexiaomeng/PyTorch-ViT-MNIST-main/solver.py", line 15, in __init__
        self.model = VisionTransformer(args).cuda()
      File "/home/ikenaga/xiexiaomeng/PyTorch-ViT-MNIST-main/model.py", line 112, in __init__
        super(Transformer, self).__init__()
    NameError: name 'Transformer' is not defined

Could you please show me your soft environment?
My soft environment is as follows:
torch==1.8.1
Python==3.7

**Comment by sachin-chhabra** [comment]
Your 

> Thanks for your great work!
> 
> I want to run your code, but there is an error.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 50, in <module>
>     main(args)
>   File "main.py", line 10, in main
>     solver = Solver(args)
>   File "/home/ikenaga/xiexiaomeng/PyTorch-ViT-MNIST-main/solver.py", line 15, in __init__
>     self.model = VisionTransformer(args).cuda()
>   File "/home/ikenaga/xiexiaomeng/PyTorch-ViT-MNIST-main/model.py", line 112, in __init__
>     super(Transformer, self).__init__()
> NameError: name 'Transformer' is not defined
> ```
> 
> Could you please show me your soft environment? My soft environment is as follows: torch==1.8.1 Python==3.7

Your environment is fine. The error was due to a small bug in the code which has been fixed now.  Please re-download the code or use the below fix and it should run fine. Thanks for pointing it out. Let me know if the issue persists. 

Fix: super(Transformer, self).__init__() -> super(VisionTransformer, self).__init__() on line 112 of model.py

**Comment by Jerryme-xxm** [comment]
Thanks for your kind reply. There is no issue now.
(I should have corrected it myself)

**Comment by sachin-chhabra** [comment]
No worries.!
